- name: OS Backup Configuration
  hosts: mariadbs
  tasks: 
    - name: Copy script to server
      copy: 
        src: backup.sh
        dest: /tmp
        mode: 0777
    - name: Execute the script
      script: /root/backup.sh
    - name: Copy Backup to ansible
      copy:
          src: /tmp/backup.log
          remote_src: true
          dest: /tmp/

        
