- name: OS Backup Configuration
  hosts: mariadbs
  tasks: 
    - name: Copy script to server
      copy: 
        src: backup.sh
        dest: /tmp
        mode: 0777
        tags:
        - simple_copy
    - name: Execute the script
        ansible.builtin.script: /tmp/backup.sh
    - name: Copy Backup to ansible
         copy:
              src: /tmp/backup.log
              remote_src: true
              dest: /tmp/

        
